server:
    port: 9090
    context-path:
    session:
      timeout: 18000 #/liuzh/

logging:
    level:
        tk.mybatis: TRACE

druid:
    url: jdbc:mysql://120.24.59.27:3306/tzxt
    username: root
    password: Anywhere1!

    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

spring:
    redis:
        host: 120.24.59.27
        #password:  #/可能没有密码/
        port: 6379
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: com.tzxt.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true

mapper:
    mappers: com.tzxt.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql